version: '3'

services: 
  frontend: 
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: frontend
    restart: always
    ports:
      - '3000:80'
    env_file:
      - .env.production